export default function Home() {
	return <></>
}

export let nonTechData = [
	{
		titleName: "Math O Mania",
		id: 10001,
		about: "",
		teamType: "Solo",
		teamSize: "1",
		time: "Dec 10, 1pm - 3pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Prelims: This round will include some Basic / Intermediate Mathematical/Aptitude Problems/Puzzles based on understanding. Participants that get qualifying marks are eligible to compete in the next round.",
			"Finals: This round will include some additional Intermediate/Advanced Math problems based on a few applications.",
			"The contestants with the highest scores will be recognized as winners.",
		],
		organizers: ["Srinath B (9789649388)", "Shreeja K (9150445617)"],
		posterUrl: "./posters/nontech/mathomania.webp",
	},
	{
		titleName: "Gaming",
		id: 10002,
		about: "",
		teamType: "Solo",
		teamSize: "1",
		time: "Dec 10, 1pm - 4:30pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"1. Rubik's Cube Solving: The winner will be the student who solves the cube the quickest.",
			"2. Battleground Games: Battlefield games to assess students' coordination and gaming prowess.",
			"3. Typing Speed: To check your typing speed, enter the given code. The syntax must be flawless, as should the indentation.",
			"A few additional mind-bending minigames will be held as rolling events in various locations.",
		],
		organizers: [
			"Logeshwaran K (7339122647)",
			"Riyaz Ahmed S (9150567713)",
		],
		posterUrl: "./posters/nontech/gaming.webp",
	},
	{
		titleName: "Fandom Quiz",
		id: 10003,
		about: "",
		teamType: "Team",
		teamSize: "2-3",
		time: "Dec 10, 2pm - 4:30pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Round 1: Preliminary round. In this round, the competitors' fundamental knowledge will be examined. The top 8 teams will advance to the next round.",
			"Round 2: Each team will receive direct questions, and they will have a set amount of time to respond to the intermediate to difficult General Knowledge questions that will be posed to them.",
			"Round 3: Rapid-fire round. The team that responds or guesses the answers to the questions promptly will receive points, regardless of how well they performed in the previous round. The winning team will be the one with the highest score.",
		],
		organizers: [
			"Aravinth kumar A M (8870335281)",
			"Vishnu A (8939430854)",
		],
		posterUrl: "./posters/nontech/quiz.webp",
	},
	{
		titleName: "Code Hunt",
		id: 10004,
		about: "",
		teamType: "Team",
		teamSize: "6",
		time: "Dec 10, 4pm - 6pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Teams in this competition must demonstrate their deductive skills. There is only one round in it. Each squad can have a maximum of six members. The players should decipher the algorithm or pseudocode to discover the hint and look for them all over the campus. The winning team is the one who discovers the ultimate code prize first.",
		],
		organizers: [
			"Sanjay Kannan M (8428929784)",
			"Srevardhani R (9360120793)",
		],
		posterUrl: "./posters/nontech/codehunt.webp",
	},
	{
		titleName: "Connexions",
		id: 10005,
		about: "",
		teamType: "Solo",
		teamSize: "1",
		time: "Dec 10, 1pm - 3pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"In this one-on-one competition, competitors must logically connect the provided images to uncover the hidden word. Two rounds make up the contest. Participants must identify the technical and non-technical phrases within the allotted time in both rounds. The terms may also be multilingual. Participants should be able to logically reason their response.",
		],
		organizers: [
			"Dafni trisha.N.R (9443192988)",
			"Geethanjali.B (6383051844)",
		],
		posterUrl: "./posters/nontech/codehunt.webp",
	},
	{
		titleName: "Charades",
		id: 10006,
		about: "",
		teamType: "Team",
		teamSize: "3",
		time: "Dec 10, 2pm - 4pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Any one person from the team can enact the given terms/words and the remaining members must guess it.",
			"Round 1: Preliminary round.  Participants are expected to guess the word/term(non-technical).",
			"Round 2: Both technical and non-technical terms will be tested. The best performing team will be selected as the  winners considering various aspects and scores.",
		],
		organizers: ["Pooja B (7395915055)", "Gnanavarshini M (6380614424)"],
		posterUrl: "./posters/nontech/charades.webp",
	},
	{
		titleName: "Art",
		id: 10007,
		about: "",
		teamType: "Solo",
		teamSize: "1",
		time: "Dec 10, 1pm - 3pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"There is only one round in this competition. The topic will be provided on the spot, and the artwork needs to be finished in 90 minutes. The necessary tools will be offered. Depending on the preferences of the participants, more equipment may be brought. The top two works of art will be recognised after evaluations of creativity and ideology.",
		],
		organizers: ["Sowmya .R (8056493106)", "Surya.S (9150986251)"],
		posterUrl: "./posters/nontech/charades.webp",
	},
	{
		titleName: "Code Cricket",
		id: 10008,
		about: "",
		teamType: "Team",
		teamSize: "3",
		time: "Dec 10, 2pm - 4:30pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"This competition aims to create the best cricket team within the available budget. There are two rounds of the competition.",
			"Round 1: This tests the competitors' knowledge of cricket.",
			"Round 2: This round essentially consists of an auction for the round 1 players who were chosen.",
		],
		organizers: ["Jagan (7540088216)", "Veejendhiran P (6383647169)"],
		posterUrl: "./posters/nontech/codecricket.webp",
	},
]

export let techData = [
	{
		titleName: "Normal Coding",
		id: 10001,
		about: "Are you the one who always thinks out of the box to solve problems? Are you passionate about programming?This is the perfect event for you. You don't need to travel long distances to show your love for programming.",
		teamType: "Solo or Team",
		teamSize: "1-2",
		time: "Dec 10, 1pm - 3pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Round 1:  Coding - Preliminary round with questions from technical domain.",
			"Round 2: Coding - Teams that qualify round 1 will compete in this final round",
			"The contestants with the highest scores will be recognized as winners.",
		],
		organizers: [
			"Meyyappan S - 9080033696",
			"Manoj S- 8248555492",
			"Madhav Krishnaa B- 7338964197",
			"Aakash LS- 9841738989",
		],
		posterUrl: "./posters/tech/normalcoding.webp",
	},
	{
		titleName: "Blind Coding",
		id: 10002,
		about: "Blind coding is a coding event in which the participants have to code without testing. The participants are allowed to test their code only once at the end",
		teamType: "Solo or Team",
		teamSize: "1-2",
		time: "Dec 10, 1pm - 4:30pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Two rounds will be conducted and the shortlisted teams from round-1 will be moved to round-2. After two rounds, the winners will be announced. ",
			"Coding languages: based on their preference. ",
		],
		organizers: ["SHRINITHA S  9003290095", "SAI ANCHANA S A  8939825128"],
		posterUrl: "./posters/tech/blindcoding.webp",
	},
	{
		titleName: "Reverse Coding",
		id: 10003,
		about: "Reverse Coding  is a competitive coding competition where participants have to think in reverse and come up with questions for the solutions",
		teamType: "Solo or Team",
		teamSize: "1-3",
		time: "Dec 10, 2pm - 4:30pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Reverse Coding has two rounds . All teams can participate in the first round. The top 5 teams from round 1 move on to round 2.",
			"Prelims - The teams can code in Java, JavaScript, C, C++, Go, Kotlin, PHP, or Python based on their preferences.",
			"At the end of the two rounds, the team with the most number of points will be declared the winner. In the case of a tie, the team that took the least amount of time to solve the questions will win.",
		],
		organizers: ["Not yet announced 😞"],
		posterUrl: "./posters/tech/reversecoding.webp",
	},
	{
		titleName: "Street Coding",
		id: 10004,
		about: "Challenge your peers and race against the clock along with disturbances and obstacles to reach the finish line. This event tests your technical knowledge on various domains and coding knowledge. Contestants with the highest number of points within the given time along with disturbances will win.",
		teamType: "Solo or Team",
		teamSize: "1-2",
		time: "Dec 10, 4pm - 6pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Round 1:  MCQ + Coding - Preliminary round with questions from technical domain.",
			"Round 2: Coding - Best performing teams from round 1 will compete in this final round.",
		],
		organizers: [
			"Balasubramanian KN - 9444876751",
			"Aadhitya A - 9884113766",
			"Kailash -9095541133",
		],
		posterUrl: "./posters/tech/streetcoding.webp",
	},
	{
		titleName: "B Plan",
		id: 10005,
		about: "You never know when the big insight will hit. You might experience it while reading, watching, or even napping peacefully. Now, if you do have that game-changing concept, the B-plan at Mutex offers you a place to discuss, debate, and reflect on it with like-minded people. You have the chance to make the change you wish to see in the world.",
		teamType: "Solo or Team",
		teamSize: "1-3",
		time: "Dec 10, 1pm - 3pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Round 1:  MCQ & Ideation questions - Preliminary round with questions from business domain.",
			"Round 2: Pitch - Best performing teams from round 1 will compete in this final round of pitching their products",
		],
		organizers: ["Vignesh A - 8825708044", "Krishnan R - 6383 551 677"],
		posterUrl: "./posters/tech/bplan.webp",
	},
	{
		titleName: "UI/UX Designing ",
		id: 10006,
		about: "",
		teamType: "Solo or Team",
		teamSize: "1-2",
		time: "Dec 10, 2pm - 4pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Round 1:  Get Started with UI/UX Online Webinar on Fundamentals on UI/UX",
			"Round 2: UI Design Event ",
		],
		organizers: ["Sneha Pillai - 7358733362", "Aarthi Iyer"],
		posterUrl: "./posters/tech/uiux.webp",
	},
	{
		titleName: "Debug",
		id: 10007,
		about: "Coding the perfect solution is a myth.  A code riddled with logical errors can make you want to fling yourself off a cliff. Do you have the eye of a true programmer to find and squash the bugs?  Find out if you have what it takes to #DeBug the code. You can edit/modify the starter code but not insert/delete any lines of code. If you do so, your solution will not be accepted even if your output matches the expected output.",
		teamType: "Solo or Team",
		teamSize: "1-2",
		time: "Dec 10, 1pm - 3pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Round 1 - PRELIMS - Pen and paper based",
			"Round 2 - FINALS - Computer based ",
		],
		organizers: [
			"Aditya Kumar - 9600194782",
			"Yashwanth V - 7010103495",
			"Vasudevakrishna - 6383943553",
		],
		posterUrl: "./posters/tech/debug.webp",
	},
	{
		titleName: "Technical Quiz",
		id: 10008,
		about: "We present you with an exquisite opportunity to showcase your brilliance in the technical field. Try brushing up all your technical concepts!",
		teamType: "Solo or Team",
		teamSize: "1-2",
		time: "Dec 10, 2pm - 4:30pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Two rounds will be conducted wherein MCQ's will be flashed. Incase of tie, a tie breaker round will decide the winner",
			"Round 1: This tests the competitors' knowledge of cricket.",
			"Round 2: This round essentially consists of an auction for the round 1 players who were chosen.",
		],
		organizers: [
			"Thrishya - 9384011184",
			"Sudharsana - 9513787803",
			"Abhijit - 98404 06710",
		],
		posterUrl: "./posters/tech/techquiz.webp",
	},
	{
		titleName: "Project Presentation",
		id: 10009,
		about: "Are you the one who thinks out of the box and implements innovative project ideas? Do you have an excellent skill to showcase your project ? This is the perfect event for you. Present your innovative projects and demonstrate your defending skills by answering the questions asked.",
		teamType: "Team",
		teamSize: "1-3",
		time: "Dec 10, 2pm - 4:30pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Project PPT and Demo(recorded or live)",
			"Round 1:  Present your innovative projects with Demo ",
		],
		organizers: ["Mohamed Fazith - 9080527253", "Rozen Berg"],
		posterUrl: "./posters/tech/projectpresentation.webp",
	},
	{
		titleName: "Query the World (DBMS)",
		id: 10010,
		about: "Trying to find your way through the data world may be hard. But, with simple queries it can be made simple. Ready to explore? We present to you this event where you will get to work on real-life database problems, improve your skill set and hack your way to the  data world.",
		teamType: "Solo or Team",
		teamSize: "1-2",
		time: "Dec 10, 2pm - 4:30pm",
		prize: ["Not yet announced 😞"],
		rounds: [
			"Round 1: MCQ - Preliminary round with questions from Database and Big data domain. Mode: Offline (Pen & paper)",
			"Round 2: Dataverse: Database querying and approaches to solve real world data problems (Winners from Round 1 are selected for Round 2). Mode: Offline (Lab PC/ Laptop with WiFi Connectivity)",
			"Language preferred: MySQL, Oracle",
		],
		organizers: ["Ezhil Mukhi S - 7305774686", "Monika - 9840867891"],
		posterUrl: "./posters/tech/dbms.webp",
	},
]
